name: Pipeline

on:
  push:
    tags:
      - v*

env:
  REPOSITORY: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY
  DIRECTORY: /home/pkgbuild
  PROJECT_NAME: hello-big

jobs:

  packaging:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Create Directory Project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: cd $DIRECTORY && mkdir -p $PROJECT_NAME

      - name: Send PKGBUILD
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -e 'ssh -p ${{ secrets.SSH_PORT }}' -avuzpg --delete
          path: ./PKGBUILD
          remote_path: ${{ env.DIRECTORY }}/${{ env.$PROJECT_NAME }}/PKGBUILD
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}

      - name: Build Package
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: cd $DIRECTORY && buildpkg -p $PROJECT_NAME -r $DIRECTORY_PKGS -w
