name: Pipeline

on:
  push:
    tags:
      - v*

env:
  EXAMPLE: xpto

jobs:

  docker_container:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Packaging
        run: |
          